language: ruby

rvm:
  - 2.3.1

before_script:
 -  bundle install

script: ./script/cibuild

env:
  global:

    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true
branches:
  only:
    - master

before_install:
- gem update --system

sudo: false
