version: '3'
services:
  react-ui:
    build:
      context: .
    ports:
      - "3069:3069"
    container_name: react-ui
    stdin_open: true
    volumes:
       - /home/marquesgabriel/home-page:/app